language: node_js
node_js:
- 6
deploy:
  provider: npm
  email: npm@heiamoss.com
  api_key:
    secure: w5nRl0dzlRiqew+Ileh5W4TDS2Dli0SEdha1Lbn35hD16JKe2qC6YosABBTeYCkcYBlk0vh0dYK1X+hNH5OL6bACriIMy4fle10/sSkLmeOY+VfyBUqxfAN3fUL8IEPRsSRLTGCLLd2JKWPwCR770MkF3OM1MDnHzucxLBFZqe9vLVSR+7UFevKCwp9tGBgtW+ORRGoP+e6U6nbLm+j2+oFIscedsE2hpKD1DRsAn+higWFODFNCEpXeGVVtRBDI8rZxRfVfNH/y6TOOwT07IHnbEG7yivUEtUEa5DRVhJLdjZDmeTUv0AfpIQG4M9uECHfa8puJZv2eMPKkUJU7huy5cMO1YDp6dThl8OL5gJYdodKXqhoebi7p4boECv7B1J/fZrHxSJ/TKCB3gakrFKS/oKjjs5carhsI2UgXllvnkjRlQPlcVq8DYejI2hdbLMEclaqnclcXsM0rkZf6z12h3cKfVjIA/DhC0AYVwWW2XTFoYgyWhOqCdqF6dZZ92Vs15uj8Cm5dLxiR7AoFOEhaoecZ4Nlrr+TFjpImuJUeiqqBKQ9fl9y7RV4g3TQYBM69io/kvFs+8c8iRSvK3lYbPp6y8eyO9oA/LuPyuN5+MrpIAxSNdpostJowgiBHZImCCW3sJUq0j4Mq1W29hzKk8xn4Yf6xINT0QFvLu/M=
  on:
    repo: joabakk/signalk-pebble-mydata
